resolver: nightly-2021-11-14

packages:
- .

extra-deps:
- aeson-2.0.2.0
- io-streams-haproxy-1.0.1.0
- snap-core-1.0.4.2
- snap-server-1.1.2.0

flags:
  http-streams:
    network-uri: true

allow-newer: true
